# Generated by Django 3.1.5 on 2021-01-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=50)),
                ('siteUrl', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('content', models.TextField()),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
